repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-build-mod
      - id: go-build-repo-mod
      - id: go-mod-tidy
      - id: go-mod-tidy-repo
      - id: go-test-mod
      - id: go-test-repo-mod
      - id: go-fmt
      - id: go-fmt-repo

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.52.2
    hooks:
      - id: golangci-lint
